version: "3"
services:
  elasticsearch:
    image: "elasticsearch:7.13.4"
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=65%
      - cluster.routing.allocation.disk.watermark.high=70%
      - xpack.security.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD="${ELASTIC_PASSWORD}"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
    networks:
      - log
  kibana:
    image: "kibana:7.13.4"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME="${ELASTIC_USERNAME}"
      - ELASTICSEARCH_PASSWORD="${ELASTIC_PASSWORD}"
    ports:
      - "5601:5601"
    networks:
      - log
    depends_on:
      - elasticsearch
networks:
  log:
    driver: bridge
volumes:
  elasticsearch:
    driver: local
